// src/constants/bookingConstants.js
export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';

export const BOOKING_LIST_MY_REQUEST = 'BOOKING_LIST_MY_REQUEST';
export const BOOKING_LIST_MY_SUCCESS = 'BOOKING_LIST_MY_SUCCESS';
export const BOOKING_LIST_MY_FAIL = 'BOOKING_LIST_MY_FAIL';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL';

export const BOOKING_CANCEL_REQUEST = 'BOOKING_CANCEL_REQUEST';
export const BOOKING_CANCEL_SUCCESS = 'BOOKING_CANCEL_SUCCESS';
export const BOOKING_CANCEL_FAIL = 'BOOKING_CANCEL_FAIL';

export const BOOKING_UPDATE_REQUEST = 'BOOKING_UPDATE_REQUEST';
export const BOOKING_UPDATE_SUCCESS = 'BOOKING_UPDATE_SUCCESS';
export const BOOKING_UPDATE_FAIL = 'BOOKING_UPDATE_FAIL';
